SELECT 
COUNT(*) TOTAL_TRANSACTION,
SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 1 ELSE 0 END 
		) AS SUCCESS_TRANSACTION,
SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE <> '00' THEN 1 ELSE 0 END 
		) AS FAILED_TRANSACTION
FROM FINTECH_TRANSACTION; 

================
================     

SELECT 
COUNT(*) TOTAL_TRANSACTION,
SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 1 ELSE 0 END 
		) AS SUCCESS_TRANSACTION,
ROUND( 
	SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 1 ELSE 0 END 
		) / COUNT(*) * 100) AS SUCCESS_RATE,		
SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE <> '00' THEN 1 ELSE 0 END 
		) AS FAILED_TRANSACTION,
ROUND(
	SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE <> '00' THEN 1 ELSE 0 END 
		) / COUNT(*) * 100) AS FAILED_RATE
FROM FINTECH_TRANSACTION; 

===============
===============



SELECT 
TRANSACTION_RESPONSE_CODE,
COUNT(*) AS TRANSACTION_COUNT,
CASE WHEN TRANSACTION_RESPONSE_CODE = '51' THEN 'INSUFFICIENT FUND' 
	 WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 'APPROVED TRANSACTION'
     WHEN TRANSACTION_RESPONSE_CODE = '05' THEN 'DO NOT HONOR'
     WHEN TRANSACTION_RESPONSE_CODE = '12' THEN 'INVALID TRANSACTION'
     WHEN TRANSACTION_RESPONSE_CODE = '54' THEN 'EXPIRED CARD'
     WHEN TRANSACTION_RESPONSE_CODE = '14' THEN 'INVALID CARD NUMBER'
     WHEN TRANSACTION_RESPONSE_CODE = '91' THEN 'SYSTEM ERROR' ELSE 'OTHER' END AS TRANSACTION_STATUS
    FROM FINTECH_TRANSACTION GROUP BY TRANSACTION_RESPONSE_CODE; 

===============
===============

SELECT DEVICE_TYPE,
COUNT(*) AS TOTAL_TRANSACTION
FROM FINTECH_TRANSACTION GROUP BY DEVICE_TYPE

===============
===============

SELECT DEVICE_TYPE,
COUNT(*) AS TOTAL_TRANSACTION,
SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 1 ELSE 0 END 
		) AS SUCCESS_TRANSACTION,
ROUND( 
	SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 1 ELSE 0 END 
		) / COUNT(*) * 100) AS SUCCESS_RATE, 		
SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE <> '00' THEN 1 ELSE 0 END 
		) AS FAILED_TRANSACTION,
ROUND(
	SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE <> '00' THEN 1 ELSE 0 END 
		) / COUNT(*) * 100) AS FAILED_RATE
FROM FINTECH_TRANSACTION GROUP BY DEVICE_TYPE order by TOTAL_TRANSACTION;


     
===============
===============

SELECT 
DEVICE_TYPE,
TRANSACTION_RESPONSE_CODE,
COUNT(*) AS TRANSACTION_COUNT,
CASE WHEN TRANSACTION_RESPONSE_CODE = '51' THEN 'INSUFFICIENT FUND' 
	 WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 'APPROVED TRANSACTION'
     WHEN TRANSACTION_RESPONSE_CODE = '05' THEN 'DO NOT HONOR'
     WHEN TRANSACTION_RESPONSE_CODE = '12' THEN 'INVALID TRANSACTION'
     WHEN TRANSACTION_RESPONSE_CODE = '54' THEN 'EXPIRED CARD'
     WHEN TRANSACTION_RESPONSE_CODE = '14' THEN 'INVALID CARD NUMBER'
     WHEN TRANSACTION_RESPONSE_CODE = '91' THEN 'SYSTEM ERROR' ELSE 'OTHER' END AS TRANSACTION_STATUS
    FROM FINTECH_TRANSACTION GROUP BY DEVICE_TYPE,TRANSACTION_RESPONSE_CODE ORDER BY DEVICE_TYPE;
	
===============
===============

select merchant_name, 
count(*) as Transaction_count,
SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 1 ELSE 0 END 
		) AS SUCCESS_TRANSACTION,
ROUND( 
	SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 1 ELSE 0 END 
		) / COUNT(*) * 100) AS SUCCESS_RATE, 		
SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE <> '00' THEN 1 ELSE 0 END 
		) AS FAILED_TRANSACTION,
ROUND(
	SUM(
	CASE WHEN TRANSACTION_RESPONSE_CODE <> '00' THEN 1 ELSE 0 END 
		) / COUNT(*) * 100) AS FAILED_RATE
from fintech_transaction group by merchant_name order by Transaction_count asc;	

===============
===============

select merchant_name,
count(*) as total_count from fintech_transaction group by merchant_name order by total_count desc LIMIT 5;

===============
===============

select merchant_name, sum(txn_amount),
count(*) as total_count from fintech_transaction group by merchant_name order by total_count desc LIMIT 5;



===============
===============

with CTE_CASE_1 as (
select count(*) as Total_count,
sum(
	case when transaction_response_code = '00' then 1 else 0 end
		) as Success_Count,
Sum(
	Case when transaction_response_code <> '00' then 1 else 0 end
		) as Failed_Count 		
        from fintech_transaction
)
select  
Success_Count / Total_count * 100 as success_rate,
Failed_Count / Total_count * 100 as Failed_rate from CTE_CASE_1;

===============
===============

select 
COUNT(*) AS TRANSACTION_COUNT,
CASE WHEN TRANSACTION_RESPONSE_CODE = '51' THEN 'INSUFFICIENT FUND' 
	 WHEN TRANSACTION_RESPONSE_CODE = '00' THEN 'APPROVED TRANSACTION'
     WHEN TRANSACTION_RESPONSE_CODE = '05' THEN 'DO NOT HONOR'
     WHEN TRANSACTION_RESPONSE_CODE = '12' THEN 'INVALID TRANSACTION'
     WHEN TRANSACTION_RESPONSE_CODE = '54' THEN 'EXPIRED CARD'
     WHEN TRANSACTION_RESPONSE_CODE = '14' THEN 'INVALID CARD NUMBER'
     WHEN TRANSACTION_RESPONSE_CODE = '91' THEN 'SYSTEM ERROR' ELSE 'OTHER' END AS TRANSACTION_STATUS
    FROM FINTECH_TRANSACTION  where TRANSACTION_RESPONSE_CODE <> '00'GROUP BY TRANSACTION_RESPONSE_CODE ORDER BY TRANSACTION_STATUS;
	
	
===============
===============	

SELECT DATE_FORMAT(transaction_date, '%m') AS MONTH,count(*) as Total_transaction
FROM fintech_transaction group by DATE_FORMAT(transaction_date, '%m') order by Total_transaction desc;

===============
===============	

	